### ISSUE TITLE
快1年了，代码呢？代码呢

### ISSUE THREAD

**Issue by mintzhao** [jpush/jpush-api-go-client#1]

**Comment by YeFatBoy** [comment]
官方加紧代码实现吧！非常需要

**Comment by xiezefan** [comment]
Hi， Dev分支中有未release版本。
https://github.com/jpush/jpush-api-go-client/tree/dev
如果急切需要的话，可以临时使用该版本。 
我们欢迎您提交Pull Request来帮助我们完善Go Server SDK
